# This workflow will install project dependencies and then run build process.
# The build process includes, style checks, linting and unit testing.

name: Build Python Project

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v2
        - name: Set up Python 3.8
          uses: actions/setup-python@v2
          with:
              python-version: 3.8
        - name: Install dependencies
          run: |
              python3 -m pip install --uprade pip
              if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi
        - name: Invoke build
          run: python3 -m invoke build
