# This workflow will install project dependencies and then run build process.
# The build process includes, style checks, linting and unit testing.

name: Build Python Project

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v2
        - name: Set up Python 3.8
          uses: actions/setup-python@v2
          with:
              python-version: 3.8.5
        - name: Install dependencies
          run: |
              python3 -m pip install --upgrade pip
              python3 -m pip install --upgrade -r requirements.txt
        - name: Debug pylint
          run: python3 -m pylint --generate-rcfile
        - name: Invoke build
          run: python3 -m invoke build
